/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#112752",
        "primary-container": "#112752",
        "secondary": "#CFB53B",
        "secondary-container": "#fee263",
        "background": "#faf9f6",
        "surface": "#faf9f6",
        "surface-container": "#efeeeb",
        "surface-container-low": "#f4f3f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2df",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#44464f",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c8fc0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#756300",
        "outline": "#757780",
        "outline-variant": "#c5c6d0",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        "inverse-primary": "#b2c6fa",
        "surface-tint": "#4a5d8b",
        "tertiary": "#0d161c",
        "tertiary-container": "#212a31",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#889199",
      },
      fontFamily: {
        "serif": ["Libre Caslon Text", "serif"],
        "sans": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.25", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
